# frozen_string_literal: true

require "rails_helper"

RSpec.describe SharedLink, type: :model do
  let(:document) { create(:document) }

  subject(:shared_link) { create(:shared_link, document: document) }

  # ── Associations ──────────────────────────────────────────────────────────

  describe "associations" do
    it { is_expected.to belong_to(:document) }
  end

  # ── Validations ───────────────────────────────────────────────────────────

  describe "validations" do
    # token and expires_at are auto-generated by callbacks, so presence is not tested directly
    it { is_expected.to validate_uniqueness_of(:token) }
  end

  # ── Callbacks ─────────────────────────────────────────────────────────────

  describe "before_validation :generate_token" do
    it "generates a UUID token when blank" do
      shared_link.valid?
      expect(shared_link.token).to match(/\A[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}\z/)
    end

    it "keeps an existing token" do
      shared_link.token = "existing-token"
      shared_link.valid?
      expect(shared_link.token).to eq("existing-token")
    end
  end

  describe "before_validation :set_expiration" do
    it "sets expires_at 15 days ahead when blank" do
      travel_to(Time.zone.local(2026, 1, 1, 12, 0, 0)) do
        link = build(:shared_link, document: document, expires_at: nil)
        link.valid?
        expect(link.expires_at).to eq(Time.zone.local(2026, 1, 16, 12, 0, 0))
      end
    end

    it "keeps an existing expiration date" do
      custom_date = 3.days.from_now
      shared_link.expires_at = custom_date
      shared_link.valid?
      expect(shared_link.expires_at).to be_within(1.second).of(custom_date)
    end
  end

  # ── Scopes ────────────────────────────────────────────────────────────────

  describe "scopes" do
    let!(:active_link)  { create(:shared_link, document: document) }
    let!(:expired_link) { create(:shared_link, :expired, document: document) }

    describe ".active" do
      it "returns only non-expired links" do
        expect(SharedLink.active).to include(active_link)
        expect(SharedLink.active).not_to include(expired_link)
      end
    end

    describe ".expired" do
      it "returns only expired links" do
        expect(SharedLink.expired).to include(expired_link)
        expect(SharedLink.expired).not_to include(active_link)
      end
    end
  end

  # ── Instance methods ──────────────────────────────────────────────────────

  describe "#expired?" do
    it "returns true when expires_at is in the past" do
      expect(build(:shared_link, :expired).expired?).to be true
    end

    it "returns false when expires_at is in the future" do
      expect(build(:shared_link, expires_at: 1.day.from_now).expired?).to be false
    end
  end

  describe "#active?" do
    it "returns true when not expired" do
      expect(build(:shared_link, expires_at: 1.day.from_now).active?).to be true
    end

    it "returns false when expired" do
      expect(build(:shared_link, :expired).active?).to be false
    end
  end
end
